export const SCHOOL_PICKER_LOADED = 'SCHOOL_PICKER_LOADED';
export const SCHOOL_PICKER_SELECT = 'SCHOOL_PICKER_SELECT';

export const ACCESS_CODE_USE_LOADING = 'ACCESS_CODE_USE_LOADING';
export const ACCESS_CODE_USE_SUCCESS = 'ACCESS_CODE_USE_SUCCESS';
export const ACCESS_CODE_USE_ERROR = 'ACCESS_CODE_USE_ERROR';
export const ACCESS_CODE_LOADING_FROM_DISK = 'ACCESS_CODE_LOADING_FROM_DISK';
export const ACCESS_CODE_LOADED_FROM_DISK = 'ACCESS_CODE_LOADED_FROM_DISK';
export const ACCESS_CODE_VALIDATION_ERROR = 'ACCESS_CODE_VALIDATION_ERROR';
export const ACCESS_CODE_SHOW_MODAL = 'ACCESS_CODE_SHOW_MODAL';
export const ACCESS_CODE_HIDE_MODAL = 'ACCESS_CODE_HIDE_MODAL';

export const APP_RESUME = 'APP_RESUME';
export const APP_PAUSE = 'APP_PAUSE';
export const APP_DESTROY = 'APP_DESTROY';
export const APP_SELECT_TAB = 'APP_SELECT_TAB';
export const APP_SELECT_INVISIBLE_TAB = 'APP_SELECT_INVISIBLE_TAB';
export const APP_SELECT_SCREEN = 'APP_SELECT_SCREEN';
export const APP_SELECT_OBJECT = 'APP_SELECT_OBJECT';
export const APP_DESELECT_SCREEN = 'APP_DESELECT_SCREEN';
export const APP_DESELECT_OBJECT = 'APP_DESELECT_OBJECT';
export const APP_JUMP_TO_ROUTE = 'APP_JUMP_TO_ROUTE';
export const APP_SCHOOL_LOADING = 'APP_SCHOOL_LOADING';
export const APP_SCHOOL_LOADED = 'APP_SCHOOL_LOADED';
export const APP_USER_LOADED = 'APP_USER_LOADED';
export const APP_IS_NEW_INSTALL_LOADED = 'APP_IS_NEW_INSTALL_LOADED';
export const APP_LAST_VERSION_LOADED = 'APP_LAST_VERSION_LOADED';
export const APP_UPDATE_PREVIOUS_TAB = 'APP_UPDATE_PREVIOUS_TAB';
export const APP_ADD_HOME_TAB_REF = 'APP_ADD_HOME_TAB_REF';
export const APP_ADD_CHILL_TAB_REF = 'APP_ADD_CHILL_TAB_REF';
export const APP_ADD_REMINDER_TAB_REF = 'APP_ADD_REMINDER_TAB_REF';
export const APP_ANONYMOUS_ID_LOADED = 'APP_ANONYMOUS_ID_LOADED';
export const APP_PINNED_OBJECTS_LOADED = 'APP_PINNED_OBJECTS_LOADED';
export const APP_PINNED_PHOTO_UPDATED = 'APP_PINNED_PHOTO_UPDATED';
export const APP_PINNED_AUDIO_UPDATED = 'APP_PINNED_AUDIO_UPDATED';
export const APP_PINNED_VOICE_UPDATED = 'APP_PINNED_VOICE_UPDATED';

export const HUD_REGISTER = 'HUD_REGISTER';
export const HUD_SHOW = 'HUD_SHOW';

export const HOME_SELECT_FILTER = 'HOME_SELECT_FILTER';
export const HOME_FEED_LOAD = 'HOME_FEED_LOAD';
export const HOME_FEED_LOADED = 'HOME_FEED_LOADED';

export const EVENTS_SELECT_FILTER = 'EVENTS_SELECT_FILTER';
export const EVENTS_FEED_LOAD = 'EVENTS_FEED_LOAD';
export const EVENTS_FEED_LOADED = 'EVENTS_FEED_LOADED';

export const HELP_FEED_LOAD = 'HELP_FEED_LOAD';
export const HELP_FEED_LOADED = 'HELP_FEED_LOADED';

export const AUDIOS_SELECT_FILTER = 'AUDIOS_SELECT_FILTER';
export const AUDIOS_FEED_LOAD = 'AUDIOS_FEED_LOAD';
export const AUDIOS_FEED_LOADED = 'AUDIOS_FEED_LOADED';
export const CHILL_VIDEOS_SELECT_FILTER = 'CHILL_VIDEOS_SELECT_FILTER';
export const CHILL_VIDEOS_FEED_LOAD = 'CHILL_VIDEOS_FEED_LOAD';
export const CHILL_VIDEOS_FEED_LOADED = 'CHILL_VIDEOS_FEED_LOADED';
export const CHILL_PHOTOS_SELECT_FILTER = 'CHILL_PHOTOS_SELECT_FILTER';
export const CHILL_PHOTOS_FEED_LOAD = 'CHILL_PHOTOS_FEED_LOAD';
export const CHILL_PHOTOS_FEED_LOADED = 'CHILL_PHOTOS_FEED_LOADED';
export const CHILL_LINKS_SELECT_FILTER = 'CHILL_LINKS_SELECT_FILTER';
export const CHILL_LINKS_FEED_LOAD = 'CHILL_LINKS_FEED_LOAD';
export const CHILL_LINKS_FEED_LOADED = 'CHILL_LINKS_FEED_LOADED';
export const CHILL_GROUPS_SELECT_FILTER = 'CHILL_GROUPS_SELECT_FILTER';
export const CHILL_GROUPS_FEED_LOAD = 'CHILL_GROUPS_FEED_LOAD';
export const CHILL_GROUPS_FEED_LOADED = 'CHILL_GROUPS_FEED_LOADED';
export const CHILL_CALLBACKS_FEED_LOAD = 'CHILL_CALLBACKS_FEED_LOAD';
export const CHILL_CALLBACKS_FEED_LOADED = 'CHILL_CALLBACKS_FEED_LOADED';

export const CHILL_FAV_SELECT_FILTER = 'CHILL_FAV_SELECT_FILTER';
export const CHILL_FAV_FEED_LOAD = 'CHILL_FAV_FEED_LOAD';
export const CHILL_FAV_FEED_LOADED = 'CHILL_FAV_FEED_LOADED';
export const CHILL_FAV_UPDATED = 'CHILL_FAV_UPDATED';
export const CHILL_REMINDERS_SELECT_FILTER = 'CHILL_REMINDERS_SELECT_FILTER';
export const CHILL_REMINDERS_FEED_LOAD = 'CHILL_REMINDERS_FEED_LOAD';
export const CHILL_REMINDERS_FEED_LOADED = 'CHILL_REMINDERS_FEED_LOADED';
export const CHILL_REMINDERS_SELECT_OBJECT = 'CHILL_REMINDERS_SELECT_OBJECT';
export const CHILL_REMINDERS_DESELECT_OBJECT = 'CHILL_REMINDERS_DESELECT_OBJECT';
export const CHILL_REMINDERS_ENABLED_UPDATED = 'CHILL_REMINDERS_ENABLED_UPDATED';
export const CHILL_REWARDS_ADD_GIVE_FILTER = 'CHILL_REWARDS_ADD_GIVE_FILTER';
export const CHILL_REWARDS_SELECT_FILTER = 'CHILL_REWARDS_SELECT_FILTER';
export const CHILL_REWARDS_FEED_LOAD = 'CHILL_REWARDS_FEED_LOAD';
export const CHILL_REWARDS_FEED_LOADED = 'CHILL_REWARDS_FEED_LOADED';
export const CHILL_REWARDS_SCAN_STARTED = 'CHILL_REWARDS_SCAN_STARTED';
export const CHILL_REWARDS_SCAN_SUCEEDED = 'CHILL_REWARDS_SCAN_SUCEEDED';
export const CHILL_REWARDS_SCAN_FAILED = 'CHILL_REWARDS_SCAN_FAILED';
export const CHILL_REWARDS_SCAN_RETRY = 'CHILL_REWARDS_SCAN_RETRY';
export const CHILL_AMSTRESSBUSTER_SELECT_FILTER = 'CHILL_AMSTRESSBUSTER_SELECT_FILTER';
export const CHILL_AMSTRESSBUSTER_FEED_LOAD = 'CHILL_AMSTRESSBUSTER_FEED_LOAD';
export const CHILL_AMSTRESSBUSTER_FEED_LOADED = 'CHILL_AMSTRESSBUSTER_FEED_LOADED';
export const CHILL_AMSTRESSBUSTER_LOGGEDIN = 'CHILL_AMSTRESSBUSTER_LOGGEDIN';
export const CHILL_BESTRESSBUSTER_SELECT_FILTER = 'CHILL_BESTRESSBUSTER_SELECT_FILTER';
export const CHILL_BESTRESSBUSTER_SIGNEDUP = 'CHILL_BESTRESSBUSTER_SIGNEDUP';
export const CHILL_BESTRESSBUSTER_UPDATE_BOTTOM_INSET = 'CHILL_BESTRESSBUSTER_UPDATE_BOTTOM_INSET';
export const LIBRARY_SELECT_FILTER = 'LIBRARY_SELECT_FILTER';
export const LIBRARY_FEED_LOAD = 'LIBRARY_FEED_LOAD';
export const LIBRARY_FEED_LOADED = 'LIBRARY_FEED_LOADED';
export const PHONE_FEED_LOAD = 'PHONE_FEED_LOAD';
export const PHONE_FEED_LOADED = 'PHONE_FEED_LOADED';
export const PHONE_FEED_UPDATED = 'PHONE_FEED_UPDATED';
export const NOTES_FEED_LOAD = 'NOTES_FEED_LOAD';
export const NOTES_FEED_LOADED = 'NOTES_FEED_LOADED';
export const NOTES_INSTRUCTION_LOADED = 'NOTES_INSTRUCTION_LOADED';

export const REWARD_POINTS_UPDATED = 'REWARD_POINTS_UPDATED';
export const REWARD_EARNED_UPDATED = 'REWARD_EARNED_UPDATED';
export const REWARD_SPENT_UPDATED = 'REWARD_SPENT_UPDATED';
export const REWARD_DONATED_UPDATED = 'REWARD_DONATED_UPDATED';
export const REWARD_FAVED_UPDATED = 'REWARD_FAVED_UPDATED';
export const REWARD_GOAL_UPDATED = 'REWARD_GOAL_UPDATED';
export const REWARD_APPLASTACTIVE_UPDATED = 'REWARD_APPLASTACTIVE_UPDATED';

export const AUDIO_PLAY_TRACK = 'AUDIO_PLAY_TRACK';
export const AUDIO_PAUSE_TRACK = 'AUDIO_PAUSE_TRACK';
export const AUDIO_STOP_TRACK = 'AUDIO_STOP_TRACK';

export const SELECTED_EVENT_SELECT = 'SELECTED_EVENT_SELECT';
export const SELECTED_EVENT_CANCEL = 'SELECTED_EVENT_CANCEL';
export const SELECTED_EVENT_SIGNEDUP = 'SELECTED_EVENT_SIGNEDUP';

export const BREATH_SELECT = 'BREATH_SELECT';
export const BREATH_CLOSE = 'BREATH_CLOSE';

export const SUBMIT_INSTRUCTION_SHOW = 'SUBMIT_INSTRUCTION_SHOW';
export const SUBMIT_INSTRUCTION_HIDE = 'SUBMIT_INSTRUCTION_HIDE';
